## Author: Keith Miller
## Date: December 15th,2014
## Name: Getting and Cleaning Data Course Project - Collect and cleaning accelerometer data from a smartphone generated by different user activity

## This script retrieves a zipped set of raw data files and outputs a single text file of tidy data. This early version will not download the zip
##but will just work in the working directory where the files have been unzipped assuming that the data resides in a directort that is passed 
## to the function
## 

run_analysis <- function() {
               
                testpath<-paste(getwd(),"test",sep="/")  ##builds path of test data 
                trainpath<-paste(getwd(),"train",sep="/") ## builds path for training data
              
        
        
        ##As this is a static set of data, it was decided to create a script that assumed the structure of the data would never change 
        # i.e. that the columns names, positions in the file are fixed 
        
        ## The script only reads in those columns required for the output i.e. those containing mean and standard deviation data
        ## this will speed up the script and use significnatly less memory
        ## This code sets up variables to use as masks in the read.table command so that it skips the columns we don't need
        ## The dataset has three types of measurement, time axial, frequency axial and regular.  
        ## Time Axial variables have 40 columns of data per measurement of which we are taking the first six, 
        ## Frequency Axial variables have 79 columns of data per measurement of which we are taking the first six,
        ## Ordinary variables have 13 colums of data of which we will take the first two
        ## in each case we are identifying the columns that we want to use by specifying that read.table read in an numeric.
        ## NULL means the column gets skipped
        
                axialt<-c(rep("numeric",6),rep("NULL",34)) ##layout of an time based axial variable.  Take the first six columns and leave 34
                axialf<-c(rep("numeric",6),rep("NULL",73)) ##layout of an frequency based axial variable.  Take the first six columns and leave 73
                ord<-c("numeric","numeric",rep("NULL",11)) ##layout of an ordinary variable, take first two columns  and leave 11
        
        ##according to features_info, there five time based axials, then five ordinaries, then 3 frequency axials and then 4 ordinaries and finally 
        ##another 7 columns data has so Total columns = 5*40 + 5*13 + 3*79 + 4*13 + 7 = 561.  Which is the number of columns in the data  
        ## After removing what we don't need, We will have a total of 66 variables, all numeric        
        ## this line sets up the mask, cols, to be used in the colClasses attribute
        ## in read.tables
                         
                cols = c(rep(axialt,5),rep(ord,5),rep(axialf,3),rep(ord,4),rep("NULL",7)) 
                    
        
        ##  Requirements 1 and 2 of the assignment:  Merge the training and the test sets to create one data set AND 
        ##  extract only the measurements on the mean and standard deviation for each measurement. 
        
        ## this code does the hard work of bringing together all the files into a single data frame i.e. 
        ## 1. Rbind Merges the training and test data text files together bringing in the subject and activity code data
        ## 2. cbind adds the colums for the Subjects and activities
        ## 3. colClasses passed to read.table Extracts only the desired columns of the mean and standard deviation for each measurement
        data<-rbind(cbind(read.table(paste(testpath,"y_test.txt",sep="/")),  ## put the activity in the first column
                          read.table(paste(testpath,"subject_test.txt",sep="/")), ##put the subject in the second column     
                          read.table(paste(testpath,"X_test.txt",sep="/"),colClasses = cols)), ## then add all data columns
                    cbind(read.table(paste(trainpath,"y_train.txt",sep="/")),## put the activity in the first column
                          read.table(paste(trainpath,"subject_train.txt",sep="/")), ##put the subject in the second column                           
                          read.table(paste(trainpath,"X_train.txt",sep="/"),colClasses = cols)) ## then add all data columns
        )
       
        
        ## Requirement 4. of the assignment  Name the Dataframe columns using the Subject ID for the Subject number, Activity for the 
        ## Activity code and the selected column names from the features.txt file to name the data columns 
        ## load the activity_labels from the directory that was passed in.  These activity labels will be used as column names in the tidy 
        ## dataset
                
                features<-read.table("features.txt",colClasses=c("NULL","character")) ##read in the features tables    
                features<-features[c(1:6,41:46,81:86,121:126,161:166,201,202,214,215,227,228,240,241,253,254,266,267,268,269,
                             270,271,345:350,424:429,503,504,516,517,529,530,542,543),]  ##select the required features        
        
                names(data)<-c("Activity_Label","Subject_ID",features) ## add names to the data.frame
        
                
        
       
        
        ##Requirement 3 of Assignment Replace Activity codes with meaningful labels from the activity_labels.txt file
                activity_labels<-read.table("activity_labels.txt")
                data[,1]<-sapply(data[,1],function(x) activity_labels[x,2])  ##sapply used to return a vector of activity labels that replace the activity codes
        
        write.table(data,"concatenated.txt")   ## write out concatenated data for verification purposes
        
        ## Requirement 5 Generate a mean by Subject/by Activty for each column in the table                
                final<-ddply(data,c("Activity_Label","Subject_ID"),numcolwise(mean) )  ##ddply groups data by Activity and Subject and then, 
                                                                        ##numcolwise takes a mean of all columns in each group
        
       
        
        ##write out a txt file of the data to a "output.txt" in the current working directory
                write.table(final,file="output.txt",row.names=FALSE)
}
        
  